Tuyuyue analysis
UM-Electra-Studio/eecs494-p3 pull request #51
Opened 2021-11-14 20:44 UTC by RichardTu1203

1. enable unity analytics and create project id in project setting (bounded with my unity account, can add members later in unity analytics)

2. create public void ReportEvent(string eventName, string key, object value) in CustomAnalyticsEvent.cs, this function will sent an event "eventName" with information as {"key", "value"} to unity analytics online. value can be any type (int, float...)

3. setup events:
 
a) record start and quit time, in MainMenu/Canvas/Menu
b) record count of player death, in Prefab/Player

2021-11-14 21:00 UTC, makersmelx requested changes
pls check all comments

2021-11-14 21:00 UTC, makersmelx commented on Assets/CustomAnalyticsEvent.cs
> +using System;
do not use GetComponent to access this component. you should consider making it a singleton and attach this component in some place that manages the game

2021-11-14 21:03 UTC, makersmelx commented
have you ever test whether the analytic works in a build?

2021-11-15 04:01 UTC, jfaro approved these changes

2021-11-17 21:51 UTC, closed without merging